server:
  port: 8099
  tomcat:
    max-threads: 1000
com:
  mahdiyar:
    dosattack:
      configuration:
        thread:
          max-pool-size: 100
          core-pool-size: 50
        rest-template:
          connection-timeout: 1000
          read-timeout: 1000