spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
    database: mysql
    open-in-view: false
  datasource:
    url: "jdbc:mysql://127.0.0.1:27028/dosattack?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true"
    username: "dosattack"
    password: "dosattack"
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8099
  tomcat:
    max-threads: 1000
  servlet:
    context-path: /api
com:
  mahdiyar:
    dosattack:
      configuration:
        thread:
          core-pool-size: 50
          max-pool-size: 100
          queue-capacity: 1000
        rest-template:
          connection-timeout: 10000
          read-timeout: 5000